
name: first_work
on:
    workflow_dispatch:
    push:
        branches:
            -main
            -'feature/*'

env:
   CONTAINER-REGISTERY: docker.io
   MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
   MONGO_USERNAME: 'superuser' 
   MONGO_PASSWORD: 'SuperPassword'

jobs:

  first_job:
       strategy:
         matrix:
          node-version: [18, 19]
          os: [ubuntu-latest]

          exclude:

            - node-version: 19
              os: ubuntu-latest

       runs-on: ${{matrix.os}}
       steps:
        - name: checkout reposc
          uses: actions/checkout@v4
        - name: SETUP NODE
          uses: actions/setup-node@v3
          with:
           node-version: 18

        - name: install dependeb
          run:
            | 
             npm install
             npm test

        - name: upload arti
          uses: actions/upload-artifact@v3
          with:
           name: test-result
           path: test-results.xml
        - name: cover
          run: npm run coverage
          continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository's code


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ vars.DOCKUSR }}
            password: ${{ secrets.DOCKPASS }}
      - name:  Build and push Docker image
        uses: docker/build-push-action@v5
        with:
         push: false
         tags: ${{ vars.DOCKUSR }}/solar:990  # Replace with your repository name
         context: . 
      - name: docker test
        run:
           |
           docker images
           docker run --name mine -d -p 3000:3000 \
            -e  MONGO_URI=$MONGO_URI \
            -e  MONGO_USERNAME=$MONGO_USERNAME \
            -e  MONGO_PASSWORD=$MONGO_PASSWORD  \
            ${{ vars.DOCKUSR }}/solar:990
           echo test
           docker ps -a
           docker inspect mine | grep IP
           echo finish
           echo done
  ghcr: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: ghcr
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ vars.GITUSR }}
         password: ${{ secrets.GHCRPASS2 }}
      - name: Build and push   

        uses: docker/build-push-action@v3
        with:
           context: .
           push: true
           tags:  ghcr.io/${{ vars.GITUSR }}/solar:990



          
