
name: first_work
on:
    workflow_dispatch:
    push:
        branches:
            -main
            -'feature/*'

env:

   MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
   MONGO_USERNAME: 'superuser' 
   MONGO_PASSWORD: 'SuperPassword'

jobs:

  first_job:
       strategy:
         matrix:
          nodejs_version: [18,19]
          operating_system: [ubuntu-latest,macos-latest]
           exclude:
            nodejs_version: 19
            operating_system: macos-latest

       runs-on: ${{matrix.operating_system}}
       steps:
        - name: checkout repoc
          uses: actions/checkout@v4
        - name: SETUP NODE
          uses: actions/setup-node@v3
          with:
           node-version: 18

        - name: install dependeb
          run:
            | 
             npm install
             npm test

        - name: upload arti
          uses: actions/upload-artifact@v3
          with:
           name: test-result
           path: test-results.xml
        - name: cover
          run: npm run coverage