
name: first_work
on:
    workflow_dispatch:
    push:
        branches:
            -main
            -'feature/*'

env:
   CONTAINER-REGISTERY: docker.io
   MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' 
   MONGO_USERNAME: 'superuser' 
   MONGO_PASSWORD: 'SuperPassword'

jobs:

  first_job:
       strategy:
         matrix:
          node-version: [18, 19]
          os: [ubuntu-latest]

          exclude:

            - node-version: 19
              os: ubuntu-latest

       runs-on: ${{matrix.os}}
       steps:
        - name: checkout reposc
          uses: actions/checkout@v4
        - name: SETUP NODE
          uses: actions/setup-node@v3
          with:
           node-version: 18

        - name: install dependeb
          run:
            | 
             npm install
             npm test

        - name: upload arti
          uses: actions/upload-artifact@v3
          with:
           name: test-result
           path: test-results.xml
        - name: cover
          run: npm run coverage
          continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository's code


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ vars.DOCKUSR }}
            password: ${{ secrets.DOCKPASS }}
      - name:  Build and push Docker image
        uses: docker/build-push-action@v5
        with:
         push: true
         tags: ${{ vars.DOCKUSR }}/solar:990  # Replace with your repository name
         context: . 
      - name: docker test
        run:
           |
           docker run --name myapp -p 3000:3000 -d \
            -e     MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData' \
            -e     MONGO_USERNAME: 'superuser' \
            -e     MONGO_PASSWORD: 'SuperPassword'  \
             ${{ vars.DOCKUSR }}/solar:990
           echo test
           docker inspect | grep IP
           echo finish

          
